---
name: Pull Request

"on":
  workflow_call:
    inputs:
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  draft-release:
    runs-on: ubuntu-latest
    outputs:
      version-name: ${{ steps.release.outputs.name }};
      version-tag: ${{ steps.release.outputs.tag_name }};
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: release-drafter/release-drafter@v5
        id: release
        with:
          config-name: release-drafter.yaml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

  lint:
    needs: draft-release
    uses: superbestfriends/github-workflow-repo/workflows/generic/lint.yaml@v1
    secrets: inherit

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: superbestfriends/github-workflow-repo/actions/setup-java@v1

      - run: mvn --batch-mode test

  package:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.get-artifact-name.outputs.stdout }}
    steps:
      - uses: superbestfriends/github-workflow-repo/actions/setup-java@v1

      - name: Get Artifact Name
        id: get-artifact-name
        run: mvn --batch-mode help:evaluate -Dexpression=project.artifactId
        shell: bash

      - run: mvn --batch-mode package -DskipTests

  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: superbestfriends/github-workflow-repo/actions/setup-java@v1

      - run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

  publish-docker:
    if: ${{ inputs.docker-build }}
    needs: package
    uses: superbestfriends/github-workflow-repo/workflows/generic/publish-docker.yaml@v1
    with:
      image-name: ${{ needs.package.outputs.name }}
      image-version: ${{ needs.draft-release.outputs.version }}-prerelease
      cache-path: target
      cache-key: ${{ github.run_id }}
