---
name: Pull Request

"on":
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  check-pr-source-branch:
    uses: superbestfriends/github-workflow-repo/workflows/generic/check_pr_source_branch.yaml@v1

  lint:
    needs: check-pr-source-branch
    uses: superbestfriends/github-workflow-repo/workflows/generic/lint.yaml@v1

  label-pr:
    needs: lint
    uses: superbestfriends/github-workflow-repo/workflows/generic/label_pr.yaml@v1

  test:
    needs: label-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - run: mvn --batch-mode test

  package:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.get-artifact-name.outputs.stdout }}
      version: ${{ steps.get-version.outputs.stdout }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - name: Get Project Version
        id: get-version
        run: mvn --batch-mode help:evaluate -Dexpression=project.version
        shell: bash

      - name: Get Artifact Name
        id: get-artifact-name
        run: mvn --batch-mode help:evaluate -Dexpression=project.artifactId
        shell: bash

      - uses: actions/cache@v5
        with:
          path: target
          key: ${{ github.run_id }}

      - run: mvn --batch-mode package

  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - uses: actions/cache@v5
        with:
          path: target
          key: ${{ github.run_id }}

      - run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

  publish-docker:
    if: ${{ inputs.docker-build }}
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v5
        with:
          path: target
          key: ${{ github.run_id }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.github-token }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          push: true
          tags: ${{ needs.package.outputs.name }}:${{ needs.package.outputs.version }}
