---
name: Pull Request

"on":
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  check-pr-source-branch:
    uses: superbestfriends/github-workflow-repo/workflows/generic/check_pr_source_branch.yaml@v1
    secrets: inherit
    with:
      source-branch: ${{ github.head_ref }}

  lint:
    needs: check-pr-source-branch
    uses: superbestfriends/github-workflow-repo/workflows/generic/lint.yaml@v1
    secrets: inherit

  label-pr:
    needs: lint
    uses: superbestfriends/github-workflow-repo/workflows/generic/label_pr.yaml@v1
    secrets: inherit

  test:
    needs: label-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - run: mvn --batch-mode test

  package:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.get-artifact-name.outputs.stdout }}
      version: ${{ steps.get-version.outputs.stdout }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - name: Get Project Version
        id: get-version
        run: mvn --batch-mode help:evaluate -Dexpression=project.version
        shell: bash

      - name: Get Artifact Name
        id: get-artifact-name
        run: mvn --batch-mode help:evaluate -Dexpression=project.artifactId
        shell: bash

      - uses: actions/cache@v5
        with:
          path: target
          key: ${{ github.run_id }}

      - run: mvn --batch-mode package -DskipTests

  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - uses: actions/cache@v5
        with:
          path: target
          key: ${{ github.run_id }}

      - run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

  publish-docker:
    if: ${{ inputs.docker-build }}
    needs: package
    uses: superbestfriends/github-workflow-repo/workflows/generic/publish-docker.yaml@v1
    with:
      image-name: ${{ needs.package.outputs.name }}
      image-version: ${{ needs.package.outputs.version }}
      cache-path: target
      cache-key: ${{ github.run_id }}
