---
name: Pull Request - Java

"on":
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  generic:
    uses: superbestfriends/github-workflow-repo/workflows/generic/on_pull_request.yaml@v1
    secrets: inherit
    with:
      source-branch: ${{ inputs.source-branch }}

  derive-versions:
    needs: generic
    if: needs.generic.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.derive-version.outputs.stdout }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - name: derive-version
        run: mvn --batch-mode help:evaluate -Dexpression=project.version

  build_and_publish:
    needs: derive-version
    if: needs.derive-version.result == 'success'
    uses: superbestfriends/github-workflow-repo/workflows/java/build_and_publish.yaml@v1
    secrets: inherit
    with:
      version: ${{ needs.derive-version.outputs.version }}
      docker-build: ${{ inputs.docker-build }}
