---
name: On Release - Java

"on":
  workflow_call:
    inputs:
      docker-build:
        type: boolean
        default: true
      release-name:
        type: string
        required: true
    secrets:
      github-token:
        required: true

jobs:
  generic:
    uses: superbestfriends/github-workflow-repo/workflows/generic/on_release.yaml@v1
    secrets: inherit

  build_and_publish:
    needs: generic
    if: needs.generic.result == 'success'
    uses: superbestfriends/github-workflow-repo/workflows/java/build_and_publish.yaml@v1
    secrets: inherit
    with:
      version: ${{ inputs.release-name }}
      next-version: ${{ needs.generic.outputs.next-version }}-SNAPSHOT
      docker-build: ${{ inputs.docker-build }}
      run-tests: false
