---
name: Push Main - Java

"on":
  workflow_call:
    inputs:
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  generic:
    uses: superbestfriends/github-workflow-repo/.github/workflows/reusable/workflows/generic/on_push_main.yaml@v1
    secrets: inherit

  build_and_publish:
    needs: generic
    if: needs.generic.result == 'success'
    uses: superbestfriends/github-workflow-repo/.github/workflows/reusable/workflows/java/build_and_publish.yaml@v1
    secrets: inherit
    with:
      version: ${{ needs.generic.outputs.release-candidate-version }}
      next-version: ${{ needs.generic.outputs.version }}-SNAPSHOT
      docker-build: ${{ inputs.docker-build }}
