---
name: Setup Java
description: "Initializes the Java Build Environment"
inputs:
  version-name:
    required: true
    description: "The version to pre bump the Maven Pom version to"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/setup-java@v3
      with:
        distribution: "oracle"
        java-version: 17
        cache: "maven"

    - uses: actions/cache@v3.2.6
      with:
        path: target
        key: ${{ github.run_id }}

    - shell: bash
      run: mvn versions:set -DnewVersion=${{ inputs.version-name }};
