---
name: Pull Request - Generic

"on":
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
    secrets:
      github-token:
        required: true

jobs:
  check-pr-source-branch:
    uses: superbestfriends/github-workflow-repo/workflows/utils/check_pr_source_branch.yaml@v1
    secrets: inherit
    with:
      source-branch: ${{ inputs.source-branch }}

  lint:
    needs: check-pr-source-branch
    if: needs.check-pr-source-branch.result == 'success'
    uses: superbestfriends/github-workflow-repo/workflows/utils/lint.yaml@v1
    secrets: inherit

  label-pr:
    needs: lint
    if: needs.lint.result == 'success'
    uses: superbestfriends/github-workflow-repo/workflows/utils/label_pr.yaml@v1
    secrets: inherit
