---
name: Lint

"on":
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  label-pr:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Label PR
        id: label_pr
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          publish: false
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
