---
name: Push Main - Java

"on":
  workflow_call:
    inputs:
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  generic:
    uses: ./.github/workflows/on_push_main_generic.yaml
    secrets: inherit

  build_and_publish:
    needs: generic
    if: needs.generic.result == 'success'
    uses: ./.github/workflows/build_and_publish_java.yaml
    secrets: inherit
    with:
      version: ${{ needs.generic.outputs.release-candidate-version }}
      next-version: ${{ needs.generic.outputs.version }}-SNAPSHOT
      docker-build: ${{ inputs.docker-build }}
