---
name: Pull Request - Generic

"on":
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
      docker-build:
        required: false
        type: boolean
        default: false
      docker-image-name:
        required: false
        type: string
    secrets:
      github-token:
        required: true

jobs:
  base:
    uses: ./.github/workflows/on_pull_request_base.yaml
    secrets: inherit
    with:
      source-branch: ${{ inputs.source-branch }}

  derive-version:
    name: Derive Version
    needs: base
    if: needs.base.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # TODO: use versions.txt or similar to get the latest actual version on main
      - name: Get Version
        id: get-version
        run: |
          version="$(git tag -l | tail -n 1)"
          version="${version:-0.0.1}"
          version="SNAPSHOT-$version-$(date +'%Y-%m-%dT%H%M%S')"
          echo version="$version" >> "$GITHUB_OUTPUT"

  publish-docker:
    needs: derive-version
    if: needs.derive-version.result == 'success' && inputs.docker-build && inputs.docker-image-name != ''
    uses: ./.github/workflows/publish_docker.yaml
    secrets: inherit
    with:
      image-version: ${{ needs.derive-version.outputs.version }}
      image-name: ${{ inputs.docker-image-name }}

  comment-pr:
    name: Comment PR
    needs: [derive-version, publish-docker]
    if: needs.publish-docker.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: comment pr
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Docker Image can be found at:
            ghcr.io/${{ github.repository_owner }}/${{ inputs.docker-image-name }}:${{ needs.derive-version.outputs.version }}
          reactions: eyes, rocket
