---
name: Pull Request - Java

"on":
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
      docker-build:
        type: boolean
        default: true
    outputs:
      image-version:
        description: The version of the resulting docker image
        value: ${{ jobs.derive-version.outputs.version }}
    secrets:
      github-token:
        required: true

jobs:
  base:
    uses: ./.github/workflows/on_pull_request_base.yaml
    secrets: inherit
    with:
      source-branch: ${{ inputs.source-branch }}

  derive-version:
    name: Derive Version
    needs: base
    if: needs.base.result == 'success'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-maven-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 17
          cache: "maven"

      - name: Get Maven Version
        id: get-maven-version
        run: echo version="$(mvn --batch-mode help:evaluate -Dexpression=project.version)" >> "$GITHUB_OUTPUT"

  build_and_publish:
    needs: derive-version
    if: needs.derive-version.result == 'success'
    uses: ./.github/workflows/build_and_publish_java.yaml
    secrets: inherit
    with:
      version: ${{ needs.derive-version.outputs.version }}
      docker-build: ${{ inputs.docker-build }}
