---
name: Push Main - Generic

"on":
  workflow_call:
    inputs:
      docker-build:
        type: boolean
        default: false
      docker-image-name:
        type: string
        required: false
    secrets:
      github-token:
        required: true

jobs:
  base:
    uses: ./.github/workflows/on_push_main_base.yaml
    secrets: inherit

  publish-docker:
    needs: base
    if: needs.base.result == 'success' && inputs.docker-build && inputs.docker-image-name != ''
    uses: ./.github/workflows/publish_docker.yaml
    secrets: inherit
    with:
      image-version: ${{ needs.base.outputs.release-candidate-version }}
      image-name: ${{ inputs.docker-image-name }}
