---
name: Push Main - Java

"on":
  workflow_call:
    inputs:
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  base:
    uses: ./.github/workflows/on_push_main_base.yaml
    secrets: inherit

  build-and-publish:
    needs: base
    if: needs.base.result == 'success'
    uses: ./.github/workflows/build_and_publish_java.yaml
    secrets: inherit
    with:
      version: ${{ needs.base.outputs.release-candidate-version }}
      next-version: ${{ needs.base.outputs.version }}-SNAPSHOT
      docker-build: ${{ inputs.docker-build }}
