---
name: Pull Request

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  on-pull-request:
    uses: ./.github/workflows/on_pull_request_generic.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      source-branch: ${{ github.head_ref }}
