---
name: Pull Request

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  on-pull-request:
    uses: superbestfriends/github-workflow-repo/.github/workflows/reusable/generic/on_pull_request.yaml@v1
