---
name: Push Main

"on":
  push:
    branches:
      - main

jobs:
  on-push-main:
    uses: ./.github/workflows/on_push_main_generic.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
