---
name: Release

"on":
  release:
    types:
      - released

jobs:
  on-release:
    uses: ./.github/workflows/on_release_generic.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
