---
name: On Release - Java

"on":
  workflow_call:
    inputs:
      release-name:
        type: string
        required: true
      docker-build:
        type: boolean
        default: true
    secrets:
      github-token:
        required: true

jobs:
  base:
    uses: ./.github/workflows/on_release_base.yaml
    secrets: inherit

  build_and_publish:
    needs: base
    if: needs.base.result == 'success'
    uses: ./.github/workflows/build_and_publish_java.yaml
    secrets: inherit
    with:
      version: ${{ inputs.release-name }}
      next-version: ${{ needs.base.outputs.next-version }}-SNAPSHOT
      docker-build: ${{ inputs.docker-build }}
      run-tests: false
