---
name: On Release - Generic

"on":
  workflow_call:
    inputs:
      release-name:
        type: string
        required: false
      docker-build:
        type: boolean
        required: false
        default: false
      docker-image-name:
        type: string
        required: false
    outputs:
      next-version:
        description: The next version after this release
        value: ${{ jobs.base.outputs.next-version }}
    secrets:
      github-token:
        required: true

jobs:
  base:
    uses: ./.github/workflows/on_release_base.yaml
    secrets: inherit

  publish-docker:
    needs: base
    if: needs.base.result == 'success' && inputs.docker-build && inputs.docker-image-name != '' && inputs.release-name != ''
    uses: ./.github/workflows/publish_docker.yaml
    secrets: inherit
    with:
      image-version: ${{ inputs.release-name }}
      image-name: ${{ inputs.docker-image-name }}
